# Generated by Django 3.2.6 on 2021-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirdropAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=56)),
                ('horizon_id', models.PositiveIntegerField()),
                ('trades_count', models.PositiveIntegerField()),
                ('lobstr_domain', models.BooleanField()),
                ('stellarterm_domain', models.BooleanField()),
                ('stellarx_domain', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
