# Generated by Django 3.2.6 on 2021-08-05 15:44
from datetime import datetime

import pytz
from django.db import migrations, models


BOOST_TRADES_COUNT = 10
BOOST_CREATED_AT = datetime(2019, 1, 1, tzinfo=pytz.UTC)


def set_boost(apps, schema_editor):
    AirdropAccount = apps.get_model('airdrop', 'AirdropAccount')

    AirdropAccount.objects.filter(trades_count__gt=BOOST_TRADES_COUNT).update(boost=models.F('boost') * 2)
    AirdropAccount.objects.filter(
        models.Q(lobstr_domain=True) |
        models.Q(stellarterm_domain=True) |
        models.Q(stellarx_domain=True)
    ).update(boost=models.F('boost') * 2)
    AirdropAccount.objects.filter(created_at__lt=BOOST_CREATED_AT).update(boost=models.F('boost') * 2)


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdropaccount',
            name='boost',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(
            set_boost,
            migrations.RunPython.noop,
        ),
    ]
