# Generated by Django 3.2.6 on 2021-08-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0002_airdropaccount_boost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirdropPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField(choices=[(1, 'Phase 1'), (2, 'Phase 2'), (3, 'Phase 3'), (4, 'Phase 4'), (5, 'Phase 5')])),
                ('balance_id', models.CharField(max_length=72)),
                ('transaction_id', models.CharField(max_length=64)),
                ('operation_id', models.CharField(max_length=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airdrop.airdropaccount')),
            ],
        ),
    ]
